In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [13]:
multipath = 15
samples = 100
doppler_spread = 1200  # [speed=30m/s, center_freq=12e9, fd=(v*f)/c]
sampling_period = 1e-2  # period in sec [sampling_rate = 1e4]

In [4]:
low, high = 0, 2 * np.pi

alpha = low + high * np.random.rand()
beta = low + high * np.random.rand()
theta = low + high * np.random.rand()

In [20]:
time = np.arange(0, samples - 1, sampling_period)
# print(len(time))
x = np.zeros(len(time))
y = np.zeros(len(time))

m = np.arange(1, multipath, 1)
print(x)
print(y)
print(m)

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
for n in range(1, samples + 1):
    xx = np.cos(((2 * m - 1) * np.pi + theta)/(4 * multipath))
    x = x + (1/np.sqrt(multipath)) * np.cos((2 * np.pi * doppler_spread * xx * n * sampling_period) + alpha)
    y = y + (1/np.sqrt(multipath)) * np.sin((2 * np.pi * doppler_spread * xx * n * sampling_period) + beta)

ValueError: operands could not be broadcast together with shapes (9900,) (14,) 